spring.cloud.function.definition: receiver
spring.cloud.stream.kafka.binder.brokers: kafka:9092
spring.cloud.stream.bindings.receiver-in-0.destination: orgChangeTopic
spring.cloud.stream.bindings.receiver-in-0.group: orgGroup              # only one copy of the message will be consumed by a service instance belonging to that group.