server:
  port:
    8081

spring:
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

spring.cloud.stream.kafka.binder.brokers: kafka:9092
spring.cloud.stream.bindings.supplier-out-0.destination: orgChangeTopic